name: markusedgar
favicon: null
layout_spectrum: 0.29512393521144986
typography_spectrum: 0.8455140306614339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#ff6e7a'
    - '#77ff70'
    - '#ffffff'
    - '#a2a2a2'
  brandStrength: 0.6875
  lightness: 0.547315965173766
  saturation: 0.130199613282457
  rhythmicContrast: 0.5
purpose: []
